package it.polimi.ingsw;

import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;

import static org.junit.jupiter.api.Assertions.*;

class DeckgridTest {
    @Test
    public void GetCardsTest() throws FileNotFoundException {
        Deckgrid d = new Deckgrid();
        DevelopmentCard card = d.getCard(1,Colour.GREEN);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(2,Colour.GREEN);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(3,Colour.GREEN);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(1,Colour.BLUE);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(2,Colour.BLUE);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(3,Colour.BLUE);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(1,Colour.YELLOW);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        card = d.getCard(2,Colour.YELLOW);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        card = d.getCard(3,Colour.YELLOW);
        assertEquals(3,card.getLevel());
        card = d.getCard(1,Colour.PURPLE);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        card = d.getCard(2,Colour.PURPLE);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        card = d.getCard(3,Colour.PURPLE);
        assertEquals(3,card.getLevel());
    }

    @Test
        public void emptyDeckTest() throws FileNotFoundException {
        Deckgrid d = new Deckgrid();
        DevelopmentCard card = d.getCard(3,Colour.PURPLE);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        card = d.getCard(3,Colour.PURPLE);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        card = d.getCard(3,Colour.PURPLE);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        card = d.getCard(3,Colour.PURPLE);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        assertNull(d.getCard(3, Colour.PURPLE));
        card = d.getCard(1,Colour.PURPLE);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        card = d.getCard(1,Colour.PURPLE);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        card = d.getCard(1,Colour.PURPLE);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        card = d.getCard(1,Colour.PURPLE);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        assertNull(d.getCard(1, Colour.PURPLE));
        card = d.getCard(2,Colour.PURPLE);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        card = d.getCard(2,Colour.PURPLE);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        card = d.getCard(2,Colour.PURPLE);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        card = d.getCard(2,Colour.PURPLE);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.PURPLE,card.getColour());
        assertNull(d.getCard(2, Colour.PURPLE));
        card = d.getCard(1,Colour.YELLOW);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        card = d.getCard(1,Colour.YELLOW);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        card = d.getCard(1,Colour.YELLOW);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        card = d.getCard(1,Colour.YELLOW);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        assertNull(d.getCard(1, Colour.YELLOW));
        card = d.getCard(2,Colour.YELLOW);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        card = d.getCard(2,Colour.YELLOW);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        card = d.getCard(2,Colour.YELLOW);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        card = d.getCard(2,Colour.YELLOW);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        assertNull(d.getCard(2, Colour.YELLOW));
        card = d.getCard(3,Colour.YELLOW);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        card = d.getCard(3,Colour.YELLOW);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        card = d.getCard(3,Colour.YELLOW);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        card = d.getCard(3,Colour.YELLOW);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.YELLOW,card.getColour());
        assertNull(d.getCard(3, Colour.YELLOW));
        card = d.getCard(1,Colour.GREEN);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(1,Colour.GREEN);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(1,Colour.GREEN);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(1,Colour.GREEN);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        assertNull(d.getCard(1, Colour.GREEN));
        card = d.getCard(2,Colour.GREEN);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(2,Colour.GREEN);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(2,Colour.GREEN);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(2,Colour.GREEN);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        assertNull(d.getCard(2, Colour.GREEN));
        card = d.getCard(3,Colour.GREEN);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(3,Colour.GREEN);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(3,Colour.GREEN);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        card = d.getCard(3,Colour.GREEN);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.GREEN,card.getColour());
        assertNull(d.getCard(3, Colour.GREEN));
        card = d.getCard(1,Colour.BLUE);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(1,Colour.BLUE);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(1,Colour.BLUE);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(1,Colour.BLUE);
        assertEquals(1,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        assertNull(d.getCard(1, Colour.BLUE));
        card = d.getCard(2,Colour.BLUE);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(2,Colour.BLUE);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(2,Colour.BLUE);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(2,Colour.BLUE);
        assertEquals(2,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        assertNull(d.getCard(2, Colour.BLUE));
        card = d.getCard(3,Colour.BLUE);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(3,Colour.BLUE);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(3,Colour.BLUE);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        card = d.getCard(3,Colour.BLUE);
        assertEquals(3,card.getLevel());
        assertEquals(Colour.BLUE,card.getColour());
        assertNull(d.getCard(3, Colour.BLUE));
    }
}